[package]
authors = ["MathxH Chen <brainfvck@foxmail.com>"]
name = "rocker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = "0.6.5"
unshare = "0.7.0"